# Generated by Django 5.2.3 on 2025-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
